### PR TITLE
fix some common test flakes

### LINKED ISSUE #61: test flake in pkg/cli/democluster: `TestTransientClusterSimulateLatencies`
https://github.com/oxidecomputer/cockroach/pull/60/checks?check_run_id=66862284254

https://buildomat.eng.oxide.computer/wg/0/details/01KKHVXH1G2DWRN5Z4MH0SVDKB/RaPStvpZCPsrRwBmAtq9CYdv0X6YtGXi9FjBTPzHjswMS9Bo/01KKHVYCA6J5XKEWSFNR9C7BAH#S2876

```
--- FAIL: TestTransientClusterSimulateLatencies (2.28s)
    test_log_scope.go:79: test logs captured to: /tmp/logTestTransientClusterSimulateLatencies1823489243
    test_log_scope.go:80: use -show-logs to present logs inline
    --- FAIL: TestTransientClusterSimulateLatencies/from_europe-west1 (0.07s)
        demo_cluster_test.go:246:
            	Error Trace:	/work/oxidecomputer/cockroach/pkg/cli/democluster/demo_cluster_test.go:246
            	Error:      	Should be true
            	Test:       	TestTransientClusterSimulateLatencies/from_europe-west1
            	Messages:   	expected duration at least 73ms, got 69.739171ms
    demo_cluster_test.go:255: -- test log scope end --
```

### PR DESCRIPTION
**Pull request by iliana**

### CODE REVIEW

File: pkg/rpc/nodedialer/nodedialer_test.go [hunk 1]
```diff
@@ -221,7 +221,7 @@ func TestConnHealthTryDial(t *testing.T) {
 	require.NoError(t, ln.popConn().Close())
 	require.Eventually(t, func() bool {
 		return nd.ConnHealthTryDial(staticNodeID, rpc.DefaultClass) == nil
-	}, time.Second, 10*time.Millisecond)
+	}, 5*time.Second, 10*time.Millisecond)
```
Comment (iliana) [inline pkg/rpc/nodedialer/nodedialer_test.go:224]: Closing the connection pops the breaker. The lines just above this allow 5 seconds for a popped breaker to recover. So why not here?

File: pkg/cli/democluster/demo_cluster_test.go [hunk 2]
```diff
@@ -147,6 +147,7 @@ func TestTransientClusterSimulateLatencies(t *testing.T) {
 	// Set up an empty 9-node cluster with simulated latencies.
 	demoCtx.SimulateLatency = true
 	demoCtx.NumNodes = 9
+	demoCtx.Localities = defaultLocalities
```
Comment (iliana) [inline pkg/cli/democluster/demo_cluster_test.go:150]: Not really sure why this fixes things and it kind of pisses me off. Best I can tell this ends up being `nil` if it's not set, so maybe this test _never_ worked properly and any simulated latencies were an accident?

File: pkg/sql/conn_executor_test.go [hunk 3]
```diff
@@ -1364,13 +1364,6 @@ ALTER TABLE t1 ADD COLUMN b INT DEFAULT 1`,
 			t.Fatalf("unexpected post commit jobs latency: %v", postCommitJobsInterval.AsFloat64())
 		}
 
-		if tc.expectNonTrivialSchemaChangeTime && postCommitJobsInterval.AsFloat64() < 0.1 {
-			t.Fatalf(
-				"expected schema changes to take longer than 0.1 seconds, took: %v",
-				postCommitJobsInterval.AsFloat64(),
-			)
-		}
-
```
Comment (iliana) [inline pkg/sql/conn_executor_test.go:1373]: Failing the test because it took less than 100ms to insert and alter 10,000 rows is ridiculous. I think the `expectNonTrivialSchemaChangeTime` is really meant to make sure that the other queries don't take too long, not to make sure that this query takes long enough...
