### PR TITLE
remove phone-home diagnostics, update checks, crash reports

### LINKED ISSUE #48: disable or remove phone home diagnostics/telemetry
CockroachDB phones home to two endpoints:

https://github.com/oxidecomputer/cockroach/blob/4088380807089c8ee92e0694bb07d9aaa7c0ebac/pkg/server/diagnostics/diagnostics.go#L33-L59

The web console also phones home in a few places, identified by `COCKROACHLABS_ADDR`:

https://github.com/oxidecomputer/cockroach/blob/4088380807089c8ee92e0694bb07d9aaa7c0ebac/pkg/ui/workspaces/db-console/src/util/cockroachlabsAPI.ts#L55-L64

We want to remove this for two reasons:

1. In the Oxide product, CockroachDB runs in a zone with no external network reachability. There's _no point_ to spending cycles on attempting to phone home.
2. It honestly seems rude to send CRL telemetry for a build of a four-year-old version they have nothing to do with and no control over, particularly given the number of instances we start (order of ~1000) during a normal integration test run of the Oxide control plane.

It is simple enough to remove the URLs or replace them with invalid hostnames, but I think it'd be better to delete the code altogether; no sense in maintaining what you can't or won't use.

### PR DESCRIPTION
**Pull request by iliana**
This removes phone-home diagnostics reporting, update checking, and crash reporting. Fixes #48.

Web console analytics and update checking was removed in #64.

The ability to produce a diagnostics report (and testing of these paths) are kept, as I think users can still manually create diagnostic reports via the HTTP API. Similarly most crash handling code paths are kept, but with the crash _reporting_ removed.

### CODE REVIEW

**Comment by iliana** [comment]
I need to test that we can safely move back and forth between clusters with and without this change, since we're removing three cluster options. But given that a handful of options were apparently removed in v22.1.2 I think it's likely fine.

File: pkg/server/server_sql.go [hunk 1]
```diff
@@ -1035,23 +1035,15 @@ func newSQLServer(ctx context.Context, cfg sqlServerArgs) (*SQLServer, error) {
 	)
 
 	reporter := &diagnostics.Reporter{
```
Comment (sudomateo) [inline pkg/server/server_sql.go:1037]: Did we want to remove this `reporter`? I see we didn't carry forward some fields like `AmbientCtx`, `Config`, `StorageClusterID`, and `LogicalClusterID`.

**Review by sudomateo — APPROVED** [review]
This looks good for me overall. Just left a question about one of the changes but it's non-blocking.

File: pkg/server/server_sql.go (hunk 1 above)
Comment (iliana) [reply pkg/server/server_sql.go:1037]: This one sticks around so that we can still take a diagnostics report manually (I think there's some way of doing that via the HTTP server). It's also used in some tests.

The only remaining public method on `diagnostics.Reporter` is `CreateReport`, which did everything but send the report and reset the report-related statistics.

Comment (sudomateo) [reply pkg/server/server_sql.go:1037]: Thanks for the clarification!
